version = 0.1

[default.deploy.parameters]
stack_name = "iyf-infra-shared-prod"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
parameter_overrides = "Stage=prod"
confirm_changeset = true
